# Generated by Django 5.2.7 on 2025-10-29 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Informe um valor entre 0 e 5!'), django.core.validators.MaxValueValidator(limit_value=5, message='Informe um valor entre 0 e 5!')])),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='actors.actor')),
            ],
        ),
    ]
