# Generated by Django 5.2.7 on 2025-10-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(choices=[('USA', 'UNITED STATES'), ('BR', 'BRAZIL')], max_length=10)),
            ],
        ),
    ]
